version: "3"
services:
  motivation_generator_app:
    build: .
    image: motivation_generator_app
    container_name: motivation_generator_app
    command: "motivation_generator_app.py"
    ports:
      - "8521:8601"
    restart: on-failure
  tasks_viewer_app:
    build: .
    image: tasks_viewer_app
    container_name: tasks_viewer_app
    command: "tasks_viewer_app.py"
    ports:
      - "8521:8602"
    restart: on-failure
  tg_bot:
    build: .
    image: tg_bot
    container_name: tg_bot
    command: "tg_bot.py"
    restart: on-failure
