version: "3"
services:
  motivation_generator_app:
    build: .
    image: educational_task_manager
    container_name: streamlit_app
    command: "streamlit_app.py"
    ports:
      - "8521:8501"
    restart: on-failure
  tg_bot:
    build: .
    image: educational_task_manager
    container_name: tg_bot
    command: "tg_bot.py"
    restart: on-failure
