version: "3"
services:
  motivation_generator_app:
    build: .
    image: educational_task_manager
    container_name: motivation_generator_app
    command: "motivation_generator_app.py"
    ports:
      - "8521:8501"
    restart: on-failure
  tasks_viewer_app:
    build: .
    image: educational_task_manager
    container_name: tasks_viewer_app
    command: "tasks_viewer_app.py"
    ports:
      - "8522:8501"
    restart: on-failure
  tg_bot:
    build: .
    image: educational_task_manager
    container_name: tg_bot
    command: "tg_bot.py"
    restart: on-failure
